[package]
name = "injector-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = "0.28.1"
indexmap = "2.2.6"
sysinfo = "0.30.13"
windows = { version = "0.58.0", features = ["Win32_Foundation"] }
